Added second paddle, paddles move, paddles stay on play surface.
eric-decompiled/pong pull request #4
Opened 2024-02-21 20:59 UTC by IvarForkbeard

2024-02-21 21:13 UTC, eric-decompiled commented
<img width="128" alt="excessive-handling" src="https://github.com/eric-decompiled/pong/assets/61591606/2b81fe46-3eb1-42d8-bada-d90ce8a59a5f">

2024-02-21 21:16 UTC, eric-decompiled commented on main.js
> +function checkInputs() {
This doesn't check inputs. Its registering an event handler that will in turn handle event inputs.

It should be called something like `registerInputHandler`

2024-02-21 21:28 UTC, eric-decompiled requested changes
main thing is the paddles move faster and faster as time progresses.

you only need to register a listner one time and it will be called whenever the event happens.

Let the browser call your function for you.

2024-02-21 21:28 UTC, eric-decompiled commented on main.js
> +  paddleOneSpeed *= -0.1;
```suggestion
  const friction = 0.1 // declare this near the top
  ...
  paddleOneSpeed *= -friction;
```

2024-02-22 15:30 UTC, eric-decompiled requested changes

2024-02-22 15:30 UTC, eric-decompiled commented on main.js
> +  registerInputHandler();
```suggestion
```

Don't register stuff in a loop.

You only need to tell the browser about how you want to handle user input one time.

Every second you will be registering 30-60 unique handlers!

2024-02-22 15:30 UTC, eric-decompiled commented on main.js
```suggestion
 registerInputHandler();
```

2024-02-22 15:30 UTC, eric-decompiled commented on main.js
> +  });
What about when the player let's go of a key? You also need to listen for `keyup`

2024-02-22 15:47 UTC, eric-decompiled commented
Here is a more detailed plan:

```js

addEventListiner('keyDown', function (key) {
  if(key.code === 'KeyS') {
    console.log('player 1 pressed down');
    player1Down = true
  }
}

addEventListiner('keyUp', function (key) {
  if(key.code === 'KeyS') {
    console.log('player 1 let go');
    player1Down = false
  }
}
```

Then in the paddle update logic check the variables:

```js
if(player1Down) {
  paddle1.x += playerOneSpeed
}
```

2024-02-22 16:49 UTC, IvarForkbeard commented on main.js
> +  });
Do I?  If friction is always trying to return the paddle to equilibrium, then letting go of the key will remove the acceleration and the paddle will brake on its own, won't it?

2024-02-22 20:07 UTC, eric-decompiled commented on main.js
> +  registerInputHandler();
Why did you resolve this?

You have a massive memory leak here

2024-02-22 20:19 UTC, eric-decompiled approved these changes
the pieces don't feel quite right, but they move + stay in bounds

I'll approve. I think next step is to detect when the ball hit the paddle, and when the ball gets passed the paddle.

Once you have the basic game then you can tune the settings to your taste

2024-02-22 20:44 UTC, merged